version: '3.8'

services:
  # PHP Apache Web Server
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - db
    environment:
      - APACHE_DOCUMENT_ROOT=/var/www/html/public
    networks:
      - l9fitness

  # MySQL Database
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: l9fitness
      MYSQL_USER: l9user
      MYSQL_PASSWORD: l9password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./database/schema.sql:/docker-entrypoint-initdb.d/01-schema.sql
      - ./database/seed.sql:/docker-entrypoint-initdb.d/02-seed.sql
      - ./database/additional_dummy_data.sql:/docker-entrypoint-initdb.d/03-dummy.sql
    networks:
      - l9fitness
    command: --default-authentication-plugin=mysql_native_password

  # phpMyAdmin (Optional)
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_USER: l9user
      PMA_PASSWORD: l9password
    depends_on:
      - db
    networks:
      - l9fitness

volumes:
  db_data:

networks:
  l9fitness:
    driver: bridge