CREATE DATABASE IF NOT EXISTS l9_gym CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE l9_gym;
CREATE TABLE user_roles (id TINYINT UNSIGNED PRIMARY KEY AUTO_INCREMENT, name VARCHAR(30) NOT NULL UNIQUE) ENGINE=InnoDB;
CREATE TABLE users (
  id INT UNSIGNED PRIMARY KEY AUTO_INCREMENT, role_id TINYINT UNSIGNED NOT NULL,
  first_name VARCHAR(80) NOT NULL, last_name VARCHAR(80) NOT NULL,
  email VARCHAR(191) NOT NULL UNIQUE, phone VARCHAR(30), emergency_contact VARCHAR(120),
  password_hash VARCHAR(255) NOT NULL, gender ENUM('male','female','other') NULL, dob DATE NULL,
  address VARCHAR(255), status ENUM('active','suspended','deleted') DEFAULT 'active',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_users_role FOREIGN KEY (role_id) REFERENCES user_roles(id)
) ENGINE=InnoDB;
CREATE TABLE membership_plans (id INT UNSIGNED PRIMARY KEY AUTO_INCREMENT, name VARCHAR(100) NOT NULL, description TEXT, duration_days SMALLINT UNSIGNED NOT NULL, price DECIMAL(10,2) NOT NULL, is_active TINYINT(1) DEFAULT 1) ENGINE=InnoDB;
CREATE TABLE classes (id INT UNSIGNED PRIMARY KEY AUTO_INCREMENT, title VARCHAR(120) NOT NULL, description TEXT, location VARCHAR(120) DEFAULT 'Main Studio', capacity SMALLINT UNSIGNED NOT NULL DEFAULT 20, start_time DATETIME NOT NULL, end_time DATETIME NOT NULL, trainer_id INT UNSIGNED NOT NULL, FOREIGN KEY (trainer_id) REFERENCES users(id), INDEX idx_classes_time (start_time, end_time)) ENGINE=InnoDB;
